### ISSUE TITLE
Discussion on which MongoDB driver to use

### ISSUE THREAD

**Issue by thjaeckle** [scullxbones/pekko-persistence-mongo#1]
The [akka-persistence-mongo](https://github.com/scullxbones/akka-persistence-mongo) persistence plugin had 2 variants to choose from regarding the used MongoDB driver:
* official [mongo-scala-driver](https://github.com/mongodb/mongo-scala-driver) (now EOL)
   * the linked dependency is EOL, the scala driver is now available at [org.mongodb.scala:mongo-scala-driver_2.13:4.8.2](https://central.sonatype.dev/artifact/org.mongodb.scala/mongo-scala-driver_2.13/4.8.2)
   * the documentation for the Scala driver is now accessible here: [http://mongodb.github.io/mongo-java-driver/4.8/driver-scala/](http://mongodb.github.io/mongo-java-driver/4.8/driver-scala/)
* [ReactiveMongo driver](https://github.com/ReactiveMongo/ReactiveMongo/)
   * last release [1.0.10](https://github.com/ReactiveMongo/ReactiveMongo/releases/tag/1.0.10): "Dec 18, 2021"

In order to have a "future proof" driver also supporting the latest MongoDB versions and in order to reduce maintenance efforts, I suggest to only support a single driver in `pekko-persistence-mongo`.
As we in [Eclipse Ditto](https://github.com/eclipse-ditto/ditto) had a very good and stable experience with the former `mongo-scala-driver` variant of `akka-persistence-mongo` - and this is the "official" driver from MongoDB I would suggest to only support this variant in the future.

As the replacement is [org.mongodb.scala:mongo-scala-driver_2.13:4.8.2](https://central.sonatype.dev/artifact/org.mongodb.scala/mongo-scala-driver_2.13/4.8.2) with documentation here: [http://mongodb.github.io/mongo-java-driver/4.8/driver-scala/](http://mongodb.github.io/mongo-java-driver/4.8/driver-scala/), I would suggest to support that driver only.

This driver supports MongoDB version 3.6 (which maybe is important for MongoDB "replacements" like AWS DynamoDB supporting only up to MongoDB 3.6 due to license issues) up to 6.1: https://www.mongodb.com/docs/drivers/java/sync/current/compatibility/

**Comment by scullxbones** [comment]
Agree totally :+1:

**Comment by thjaeckle** [comment]
@scullxbones I managed to work on an initial migration .. but did not yet e.g. look into tests.
Will do that next ;)

If you already have feedback, that would be great.

**Comment by bdoyle0182** [comment]
@thjaeckle will data from akka persistence mongo that used reactive-mongo be compatible with this using the mongo scala driver?

**Comment by scullxbones** [comment]
@bdoyle0182 when I wrote the original code I went through an effort to make sure driver switching was easy and backward compatible. That said, please verify for your use case.

**Comment by bdoyle0182** [comment]
Thanks for the forward thinking @scullxbones . I didn't realize this repo already existed, I can start testing and report back if things look good.
