### ISSUE TITLE
Scala 3 support?

### ISSUE THREAD

**Issue by pjfanning** [scullxbones/pekko-persistence-mongo#13]
Would it be possible to support Scala 3? The core Pekko libs support it.

**Comment by thjaeckle** [comment]
Sure, if someone needs Scala 3 support in this library, we would happily accept that.
I have neither the need nor the experience in Scala to do that.

**Comment by pjfanning** [comment]
The use of `"org.mongodb.scala" %% "mongo-scala-driver"` blocks this - that project does not support Scala 3.

**Comment by SakulK** [comment]
@thjaeckle any chance you could take a look at https://github.com/scullxbones/pekko-persistence-mongo/pull/15 ? :slightly_smiling_face:
