### ISSUE TITLE
No snapshots published

### ISSUE THREAD

**Issue by ryandavidhartman** [scullxbones/pekko-persistence-mongo#3]
Hey,

I'm really excited to use this!  But it seems like you aren't publishing any snapshots yet.  Of course I can do a clone and make the jar, which I have,  but it would be cool to just grab the jar that you publish. 

Thanks for making this awesome project!

**Comment by thjaeckle** [comment]
@ryandavidhartman would a snapshot published to GitHub packages maven repo be sufficient?

@scullxbones I did not yet look how we want to publish to maven central once we do a release.
I assume that we would need to configure/add a groupID in Sonatype central for which we would be able to release artifacts?

**Comment by ryandavidhartman** [comment]
"would a snapshot published to GitHub packages maven repo be sufficient?"  Yes indeed!  Thank you!

**Comment by scullxbones** [comment]
@thjaeckle I have a `groupId` already, it may just work as-is with the existing `pre-release` `post-release` scripts.  IMO, it would be much better to build out github actions though to fully automate it.

**Comment by thjaeckle** [comment]
> @thjaeckle I have a `groupId` already, it may just work as-is with the existing `pre-release` `post-release` scripts. IMO, it would be much better to build out github actions though to fully automate it.

@scullxbones I tried to give it a shot in PR #4 publishing the SNAPSHOT to Sonatype / Maven central.
* It however of course failed due to not being authorized (see [this run](https://github.com/scullxbones/pekko-persistence-mongo/actions/runs/5359743350/jobs/9723732150) )
* And I assume that your GPG key would also be required to sign the artifacts correctly before publishing.

Both based on the docs I found: https://www.scala-sbt.org/release/docs/Using-Sonatype.html#step+3%3A+Credentials

In the meantime, Apache Pekko 1.0.0-RC2 is released, so a published snapshot or even also a RC of `pekko-persistence-mongo` would indeed be great :)
Do you think you could configure the credentials and GPG key as secrets of this repo (I am no admin, so I don't see them anyhow)?
Or do you have another idea?

**Comment by thjaeckle** [comment]
@scullxbones may I *ping* you again regarding the Sonatype central publishing?
If your time allows it, finding a solution to publish the artifacts of "pekko-persistence-mongo" would be awesome.

**Comment by scullxbones** [comment]
Hi @thjaeckle, thanks for the reminder.  I was looking into this, I managed to lose the boot record into my dual boot linux machine with my GPG keypair on it (among other things).  I think I can replace it, but I want to see if there's a way to get back into that.  Is this totally blocked?  I was thinking there was an interim solution.

**Comment by thjaeckle** [comment]
@scullxbones oh, I see. Too bad.
Well, I thought the interim way would be to publish to GitHub packages, but then I saw that everything for publishing snapshots to Central should already be in place.
And publishing from sbt to GitHub packages is more effort.

But I can try to look into that.

**Comment by bdoyle0182** [comment]
Seeing as Pekko 1.0.0 was officially released this week, it would be great to get an initial release out. I didn't realize work had already commenced on this, thank you for the effort so far the repo looks good. Is there anything I can help with? It seems like you both would be interested in bringing this under apache pekko, I could start the discussion on their willingness to accept it?

My one suggestion on the artifact publishing would be to drop `-scala`. Pekko is going for a lot of consistency on naming of extensions and their format for persistence plugins seems to be `pekko-persistence-${db}`

**Comment by thjaeckle** [comment]
> Is there anything I can help with? It seems like you both would be interested in bringing this under apache pekko, I could start the discussion on their willingness to accept it?

That would be very helpful and highly appreciated - I assumed that after 1.0.0 the Apache Pekko team would be open to discuss further plugins to be added to the project scope.

> My one suggestion on the artifact publishing would be to drop `-scala`.

Yes, good proposal - I will do so in #5

**Comment by thjaeckle** [comment]
I still did not manage to get the SNAPSHOT artifacts published to GitHub packages and am out of ideas now ..
If anyone has a suggestion, I would be grateful .. :)

**Comment by bdoyle0182** [comment]
I started a thread on the pekko mailing list. It spawned a good conversation, but in short the project is way too busy right now with all of the initial project work to consider a community discussion on what is suitable to bring in under apache. So for now should move forward with just getting an initial release out. I can potentially help look in a few days at github packages

https://lists.apache.org/thread/57d65cjwtgq4tqoq2tx9hc1zpw9s9s5n

**Comment by scullxbones** [comment]
Thanks for linking that discussion. I never could get the Alka team interested in taking on this plug in, the focus was on yes dynamo but mainly Cassandra. As to the stars, a bit of humility in that this plug in has been around since almost the beginning of akka persistence. I think they just reflect the age of the project.

In any case, the consensus makes sense. We'll get a 1.0 out and see where things go from there.

**Comment by ryandavidhartman** [comment]
hey gang,  Not to dog pile on here but I'll mention that with the latest commit to master it is no longer possible publish locally.  Just an FYI, I know you are working hard on the issue!

**Comment by thjaeckle** [comment]
@ryandavidhartman local publishing should work again, sorry for that ..
Publishing to GH Packages still does not work :/

**Comment by scullxbones** [comment]
@ryandavidhartman @thjaeckle 

Can someone confirm that a `1.0.0-SNAPSHOT` is available?  It looks like it should be.

**Comment by thjaeckle** [comment]
@scullxbones thanks for your help on this 👍 

That looks real good, yes:
https://oss.sonatype.org/content/repositories/snapshots/com/github/scullxbones/pekko-persistence-mongodb_2.13/1.0.0-SNAPSHOT/

I noticed that also the `pekko-persistence-mongo-tools` were published - I think this was not done for "akka-persistence-mongo", could that be?
https://oss.sonatype.org/content/repositories/snapshots/com/github/scullxbones/pekko-persistence-mongo-tools_2.13/1.0.0-SNAPSHOT/

**Comment by bdoyle0182** [comment]
I was able to pull the 1.0.0-SNAPSHOT into a project from `"https://oss.sonatype.org/content/repositories/snapshots"`

**Comment by bdoyle0182** [comment]
also just fyi the pekko team found a minor internal issue with the 1.0.0 release that doesn't affect users of the package, but are quickly getting a 1.0.1 release in the next couple days. I would wait to do the first release of this until 1.0.1 is released.

**Comment by scullxbones** [comment]
I can turn off the publish of the tools module, that's no problem. My plan was to delete all of the flags first.

We'll test again on an actual release, which is triggered by tagging apparently. I don't expect a problem though.

**Comment by bdoyle0182** [comment]
pekko 1.0.1 is released now so that should unblock any initial release

**Comment by ryandavidhartman** [comment]
Amazing thank you so much!

**Comment by thjaeckle** [comment]
I updated to Pekko 1.0.1 in #8

**Comment by thjaeckle** [comment]
@ryandavidhartman or @bdoyle0182 did someone have the chance and time yet to verify that the plugin is working as drop in replacement for the  akka-persistence-mongo plugin?

I unfortunately did not yet, as my project eg also relies on akka-management which is not yet released as Pekko.

**Comment by scullxbones** [comment]
I think we can release a `1.0.0` if we can get some feedback on the snapshot.

**Comment by ryandavidhartman** [comment]
My project (sadly not open source or l'd link) is successfully using your
project!  *But* this is a green field project so I've been using
pekko-persistence-mongo from the start, rather than as a drop in
replacement.

**Comment by scullxbones** [comment]
That's a good data point, thanks @ryandavidhartman - is it in production?

**Comment by ryandavidhartman** [comment]
Not yet, the app is still in development mode.  Scheduled for production
launch at the end of Q3

**Comment by scullxbones** [comment]
As you can see from the commits on the main branch, am fighting the release plugin, will need a bit of time to troubleshoot this.

**Comment by thjaeckle** [comment]
@alstanchev could you already verify that the 1.0.0-SNAPSHOT is working with Ditto on Pekko?

**Comment by alstanchev** [comment]
@thjaeckle It seems so, but I am having some configuration issues with the system test. Next week I will be able to confirm.

**Comment by bdoyle0182** [comment]
@scullxbones is it possible we can follow semver `major.minor.patch` like the akka version
