### ISSUE TITLE
pekko label on repo

### ISSUE THREAD

**Issue by pjfanning** [scullxbones/pekko-persistence-mongo#6]
Thanks for your work on this project.

Would it be possible to add GitHub labels to the project? `pekko` and `pekko-persistence` would be useful. It's good for apps like https://index.scala-lang.org/ which uses the labels to categorise the Scala libs.

**Comment by thjaeckle** [comment]
Sounds good.
@scullxbones could you do that? I don't have permissions to do so.

**Comment by scullxbones** [comment]
No problem. Done.
